package ru.rtk.crm.interaction;

public enum CommandOperation {
    CREATE_INTERACTION,
    TRANSITION_INTERACTION,
    COMMENT_INTERACTION,
    EDIT_INTERACTION_STAGES,
    UPDATE_INTERACTION_PLAN,
    CREATE_WORKFLOW_TEMPLATE,
    UPDATE_WORKFLOW_TEMPLATE,
    DELETE_WORKFLOW_TEMPLATE,
    UPLOAD_ATTACHMENT,
    APPLY_CATALOG_IMPORT,
    CREATE_CONTACT,
    ASSIGN_ORGANIZATION,
    UPDATE_CRM_PROFILE,
    CREATE_TEAM,
    RENAME_TEAM,
    TRANSFER_ORGANIZATION_TEAM,
    APPLY_SOURCE_RECORD
}
