package ru.rtk.crm.interaction;

public enum InteractionEventType {
    CREATED,
    TRANSITIONED,
    COMMENTED,
    STAGES_EDITED,
    PLAN_UPDATED,
    DETAILS_UPDATED,
    STATUS_CHANGED,
    AGREEMENT_UPDATED,
    ATTACHMENT_DELETED,
    STAGE_COMPLETED,
    STAGE_COMPLETION_CLEARED
}
