Foreground true
User clamav
LocalSocket /tmp/clamd.sock
FixStaleSocket true
TCPSocket 3310
MaxConnectionQueueLength 30
ReadTimeout 120
CommandReadTimeout 30
StreamMaxLength 25M
MaxScanSize 25M
MaxFileSize 25M
MaxRecursion 16
MaxFiles 10000
AlertEncryptedArchive yes
AlertExceedsMax yes
LogTime true
